<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ai.nizo.memory</groupId>
        <artifactId>nizo-memory-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>nizo-memory-client</artifactId>
    <name>Nizo Memory :: Client</name>

    <dependencies>
        <dependency>
            <groupId>ai.nizo.memory</groupId>
            <artifactId>nizo-memory-core</artifactId>
        </dependency>
    </dependencies>
</project>
